from pydantic import BaseModel, Field

from config import CONFIDENCE_THRESHOLD

class RetrievalAnalysisModel(BaseModel):
    """
    Model for retrieval analysis data.
    """
    confidence: float = Field(description="""
        Confidence score of the retrieval analysis. It reflects how accurate and precise are the chunks retrieved 
        compared with the question provided in the ticket.
        A 100 indicates that the question is answered by the given chunks very accurately, 
        while a 0 indicates that the question is not answered by the given chunks at all.""")
    answer: str = Field(description="""Answer generated by the model based on the retrieved chunks.
        If confidence is lower than the configured threshold ({CONFIDENCE_THRESHOLD}), the answer should be that the ticket
        will be escalated to human intervention.""")