from pydantic import BaseModel, Field

from config import CONFIDENCE_THRESHOLD

class Source(BaseModel):
    """Model that documents a source used in the response"""
    format: str = Field(description="Format of the document used as a source")
    name: str = Field(description="Name of the document used as a source")
    content: str = Field(description="""Content of the source used as a resolution for the ticket issue""")

class ClassificationInfo(BaseModel):
    """Reasoning of the confidence and score"""
    score: float = Field(description="""
        Confidence score of the retrieval analysis. It reflects how accurate and precise are the chunks retrieved 
        compared with the question provided in the ticket.
        A 1 indicates that the question is answered by the given chunks very accurately, 
        while a 0 indicates that the question is not answered by the given chunks at all.""")
    justification: float = Field(description=f"""
        Justification on why the score is the value it is. If the score is lower than threshold {CONFIDENCE_THRESHOLD},
        the ticket will be escalated to human, because it is considered that the documentation
        used to solve it, has not enough information.""")

class RetrievalAnalysisModel(BaseModel):
    """
    Model for retrieval analysis data.
    """
    classification: ClassificationInfo = Field(description="""
        Score and justification given to see if the answer is able to be solved using the available
        documentation""")
    answer: str = Field(description=f"""Answer generated by the model based on the retrieved chunks.
        If confidence is lower than the configured threshold ({CONFIDENCE_THRESHOLD}), the answer should be that the ticket
        will be escalated to human intervention.""")
    sources: list[Source] = Field(description="None or a list of sources used to solve the ticket issue") 